export type IconType = {
    type:
        | 'chats'
        | 'close'
        | 'exit'
        | 'fs'
        | 'fsexit'
        | 'login'
        | 'plus'
        | 'profile'
        | 'registration'
        | 'roundarrow'
        | 'search'
        | 'send'
        | 'video'
        | 'slashcall'
        | 'call'
        | 'monitor'
        | 'changecam'
        | 'gallery'
        | 'camera'
        | 'mic'
        | 'invite'
        | 'arrowUp';
};
