export const ENGLISH = {
    buttons: {
        home: 'HOME',
        ready: 'READY',
        close: 'CLOSE',
        switch: 'SWITCH',
        update: 'UPDATE',
        forum: 'FORUM',
        leaders: 'LEADERS',
        profile: 'PROFILE',
        logout: 'LOG OUT',
        login: 'LOG IN',
        signup: 'SIGN UP',
        play: 'PLAY',
        auto: 'AUTO',
        reset: 'RESET',
        start: 'START',
        send: 'SEND',
        editprofile: 'EDIT PROFILE',
        editpass: 'EDIT PASSWORD',
        confirm: 'CONFIRM',
        back: 'BACK',
        change: 'RU',
        add: 'ADD',
        edit: 'EDIT',
        delete: 'DELETE',
        ships: 'SHIPS',
        random: 'RANDOM',
    },
    labels: {
        chats: 'CHATS',
        finder: 'INVITES',
        menu: 'MENU',
        forum: 'FORUM',
        leaders: 'LEADERBOARD',
        player: 'PLAYER',
        wins: 'WINS',
        defeats: 'DEFEATS',
        points: 'POINTS',
        default: 'DEFAULT',
        custom: 'CUSTOM',
        information: 'Information',
        online: 'ONLINE',
        classic: 'CLASSIC',
        theme: 'Theme',
        add: 'Add new TOPIC',
        editTopic: 'Edit TOPIC',
        editComment: 'Edit Comment',
        deleteTopic: 'Delete TOPIC',
        deleteComment: 'Delete Comment',
        auth: 'AUTHORIZATION',
        reg: 'REGISTRATION',
        find: 'FIND',
    },
    text: {
        cancelGame: 'The game was canceled',
        waiting: 'Waiting for your opponent',
        closeGame: 'Do you want to close the game?',
        editTopic: 'Describe your topic',
        editComment: 'Describe your comment',
        add: 'Describe your topic',
        avatar: 'Добавь аватар со своего компьютера',
        information:
            '"BATTLESHIP" is a game for two participants in which players take turns calling coordinates on an unknown opponent\'s map. If the opponent has a ship at these coordinates (the coordinates are occupied), then the ship or part of it is "drowned", and the hit gets the right to make another move. The player\'s goal is to sink all enemy ships first.',
        togglemode: 'Toggle play mode!',
        forum: 'Send comment...',
        deleteTopic: 'Do you want to delete the topic?',
        deleteComment: 'Do you want to delete the comment?',
    },
};
